INSERT INTO intranet.`role` (id,name,description) VALUES 
(1,'CEO','Chief Executive Officer'),
(2,'Direction','ANASTec Director'),
(3,'CFO','Chief Finance Officer'),
(4,'GM','General Manager'),
(5,'MNG','Manager'),
(6,'TM','Technical Manager'),
(7,'SBD','Sales and Business Developer'),
(8,'ITS-PLC','ITS and PLC Engineer'),
(9,'ITS-ELV','ITS and ELV Engineer'),
(10,'NTWK','Network'),
(11,'CAD','CAD Engineer'),
(12,'GTR','Gantry Engineer'),
(13,'SW','Software Manager'),
(14,'DVLP','Software Developer'),
(15,'PM','Project Engineer'),
(16,'PLN','Planning Engineer'),
(17,'O&M','Tunnel O&M Manager'),
(18,'S-OP','Senior Operator'),
(19,'OP','Operator'),
(20,'ELV','ELV Engineer'),
(21,'CTRL','Control Engineer'),
(22,'ELCTR','Electrical Engineer'),
(23,'S-CVL','Senior Civil Engineer'),
(24,'CVL','Civil Engineer'),
(25,'S-ACC','Senior Accountant'),
(26,'ACC', 'Accountant'),
(27,'PRCR', 'Procurement Er.'),
(28,'HR', 'Admin & HR Coordinator'),
(29,'REC', 'Receptionist'),
(30,'OFF', 'Office Coordinator'),
(31,'LGST', 'Logistic In Charge'),
(32,'DRV', 'Driver'),
(33,'S-DC', 'Senior Document Controller'),
(34,'DC', 'Document Controller')
;
